[package]
authors = ["Andrei Orlov"]
edition = "2018"
name = "actix-redis-example"
version = "0.1.0"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.19"
futures = "0.1.26"
redis = "0.10.0"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
time = "0.1.42"
